### ISSUE TITLE
Detecting number of MPI processes

### ISSUE THREAD

**Issue by mancellin** [dNamiLab/dNami#20]
As a new user, I've been mildly frustrated by errors due to a mismatch between the content of `compute.py` and the command `mpirun`. For instance, when I try to run `mpirun -np 1 python compute.py` where `compute.py` contains `with_proc = [2]`.

It seems that an error message is planned in the code for that situation: 
https://github.com/dNamiLab/dNami/blob/fc2e4f044254dd59a63d150a5cbd0ee69d733f38/src/src_py/dnami_mpi.py#L49-L51

but on my machine, the execution fails earlier and I get the following obscure error message:
```
Traceback (most recent call last):
  File "/home/ubuntu/code/dNami/wrk/compute.py", line 82, in <module>
    dtree = dn.start_mpi(dtree)
  File "/home/ubuntu/code/dNami/src/src_py/dnami.py", line 145, in start_mpi
    dMpi = type_mpi(tree)
  File "/home/ubuntu/code/dNami/src/src_py/dnami_mpi.py", line 37, in __init__
    self.comm_torus = MPI.COMM_WORLD.Create_cart(
  File "mpi4py/MPI/Comm.pyx", line 1319, in mpi4py.MPI.Intracomm.Create_cart
mpi4py.MPI.Exception: MPI_ERR_ARG: invalid argument of some other kind
```

**Comment by mancellin** [comment]
By the way, why not raise an exception instead of using `sys.exit()`? Is `sys.exit()` better when running a MPI job? (I'm not very familiar with mpi4py).

**Comment by etouber** [comment]
Hi @mancellin, thank you for pointing this out. The planned error message was erroneously placed after the COMM_WORLD.Create_cart() call so it was not reached before the error message you saw is thrown up. We've modified the order of checks so that the user should be clearly informed if the number of requested cores does not match that in the compute.
